
package server.calculator;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-11-27T14:23:32.949-02:00
 * Generated source version: 3.2.1
 * 
 */
 
public class Calculator_PortTypeServer{

    protected Calculator_PortTypeServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new server.calculator.Calculator();
        String address = "http://localhost:9090/CalculatorPort";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new Calculator_PortTypeServer();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
 
 